name : Main CI
run-name : ${{github.actor}} is running the main CI
on : 
  push :
    branches : [main]
  pull_request :
    branches : [main]
jobs : 
  test-backend : 
    runs-on : ubuntu-latest

    strategy:
      matrix :
        node-version : ['18.x']

    steps : 
      - name : Use Node.js ${{matrix.node-version}}
        uses : actions/setup-node@v3
        with : 
          node-version : "18.x"

      - name : Checkout
        uses : actions/checkout@v3
        
      - name : Get in backend folder
        run : cd back
        working-directory : ./back
      - run : ls
      - run : npm install
      - run : npm test
