name : Main CI
run-name : ${{github.actor}} is running the main CI
on : 
  push :
    branches : [main]
  pull_request :
    branches : [main]
jobs : 
  test-backend : 
    runs-on : ubuntu-latest

    strategy:
      matrix :
        node-version : ['18.x']

    steps : 
      - uses : actions/setup-node@v3
        with : 
          node-version : "18.x"
      - uses : actions/checkout@v3
      - run : ls
      - run : npm install
        run : npm test
        working-directory : ./back
