name : Main CI
run-name : ${{github.actor}} is running the main CI
on : 
  push :
    branches : [main]
  pull_request :
    branches : [main]
jobs : 
  first-test : 
    runs-on : ubuntu-latest
    steps : 
      - run : echo "test ok"
  
  test-backend : 
    runs-on : ubuntu-latest

    strategy:
      matrix :
        node-version : ['18.x']

    steps : 
      - uses : actions/checkout@v3
      - name : Use Node.js ${{matrix.node-version}}
        uses : actions/setup-node@v3
        with : 
          node-version : "18.x"
      - run : npm test -w backend
