name : Main CI
run-name : ${{github.actor}} is running the main CI
on : 
  push :
    branches : [main]
  pull_request :
    branches : [main]
jobs : 
  first-test : 
    runs-on : ubuntu-latest
    steps : 
      - uses : echo "test ok"